# Generated by Django 5.0.9 on 2024-11-27 21:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_barra', models.CharField(max_length=20, unique=True, verbose_name='Código de Barra')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, default='', null=True, verbose_name='Descripción')),
                ('imagen_principal', models.ImageField(default='', upload_to='productos/', verbose_name='Imagen Principal')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Opcional 2')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Opcional 3')),
                ('imagen_4', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Opcional 4')),
                ('imagen_5', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Opcional 5')),
                ('imagen_6', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Opcional 6')),
                ('categoria', models.CharField(choices=[('VIDEOJUEGOS', [('Videojuegos PS3', 'PlayStation 3'), ('Videojuegos PS4', 'PlayStation 4'), ('Videojuegos PS5', 'PlayStation 5'), ('Videojuegos XBOX 360', 'Xbox 360'), ('Videojuegos XBOX ONE', 'Xbox One'), ('Videojuegos XBOX SERIES', 'Xbox Series'), ('Videojuegos Nintendo 3DS', 'Nintendo 3DS'), ('Videojuegos WII', 'Nintendo Wii'), ('Videojuegos WII U', 'Nintendo Wii U'), ('Videojuegos Nintendo SWITCH', 'Nintendo Switch'), ('Videojuegos para PC', 'PC')]), ('CONSOLAS', [('Ps4 Consolas', 'Consola PlayStation 4'), ('Ps5 Consolas', 'Consola PlayStation 5'), ('Xbox One Consolas', 'Consola Xbox One'), ('Xbox Series Consolas', 'Consola Xbox Series'), ('Wii U Consolas', 'Consola Wii U'), ('Switch Consolas', 'Consola Switch')]), ('ACCESORIOS', [('Accesorios Psp', 'PSP'), ('Accesorios Ps Vita', 'PlayStation Vita'), ('Accesorios PS1', 'PlayStation 1'), ('Accesorios PS2', 'PlayStation 2'), ('Accesorios PS3', 'PlayStation 3'), ('Accesorios PS4', 'PlayStation 4'), ('Accesorios PS5', 'PlayStation 5'), ('Accesorios XBOX 360', 'Xbox 360'), ('Accesorios XBOX ONE', 'Xbox One'), ('Accesorios XBOX SERIES', 'Xbox Series'), ('Accesorios Nintendo 3DS', 'Nintendo 3DS'), ('Accesorios WII U', 'Wii U'), ('Accesorios Nintendo SWITCH', 'Switch')]), ('FIGURAS', [('Figuras Funko', 'Funko Pop'), ('Figuras Amiibo', 'Amiibo')])], max_length=40, verbose_name='Categoría')),
                ('genero', models.CharField(choices=[('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('RPG', 'RPG'), ('DEPORTES', 'Deportes'), ('CARRERAS', 'Carreras'), ('ESTRATEGIA', 'Estrategia'), ('SIMULACION', 'Simulación'), ('PUZZLE', 'Puzzle'), ('TERROR', 'Terror'), ('CONSOLAS', 'Consolas'), ('FIGURAS', 'Figuras'), ('ACCESORIOS', 'Accesorios'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Género')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(default='', max_length=100)),
                ('rut', models.CharField(default='Rut no especificado', max_length=12, unique=True)),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=120, verbose_name='Dirección')),
                ('region', models.CharField(default='Región no especificada', max_length=100)),
                ('ciudad', models.CharField(default='Ciudad no especificada', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appPrincipal.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('Respondido', 'Respondido')], default='Abierto', max_length=20)),
                ('asunto', models.CharField(default='No especificado', max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='appPrincipal.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='appPrincipal.usuario'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio', models.PositiveIntegerField(default=0)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('Sin Enviar', 'Sin Enviar'), ('Enviado', 'Enviado')], default='Sin Enviar', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_envio', models.CharField(choices=[('domicilio', 'Envío a domicilio'), ('tienda', 'Retiro en tienda')], default='', max_length=10)),
                ('direccion_envio', models.TextField(blank=True, null=True)),
                ('carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.carrito')),
                ('productos', models.ManyToManyField(related_name='ventas', to='appPrincipal.itemcarritoproducto', verbose_name='Productos')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='appPrincipal.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('puntuacion', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Puntuación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='appPrincipal.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='appPrincipal.usuario')),
            ],
            options={
                'verbose_name': 'Opinión',
                'verbose_name_plural': 'Opiniones',
                'unique_together': {('usuario', 'producto')},
            },
        ),
    ]
