# Generated by Django 5.0.9 on 2024-11-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20, null=True),
        ),
    ]
