# Generated by Django 5.0.9 on 2024-11-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0002_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='region',
            field=models.CharField(default='Región no especificada', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(default='Región no especificada', max_length=100),
        ),
    ]
