# Generated by Django 5.0.9 on 2024-11-28 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0002_reclamo_respuesta'),
        ('appPrincipal', '0002_remove_venta_productos_productoventa'),
    ]

    operations = [
    ]
