# Generated by Django 5.0.9 on 2024-11-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0002_alter_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='tipo',
            field=models.CharField(choices=[('E', 'En Proceso'), ('C', 'Completado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
