# Generated by Django 5.0.9 on 2024-11-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0003_usuario_region_alter_usuario_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(default='Ciudad no especificada', max_length=100),
        ),
    ]
