# Generated by Django 5.0.9 on 2024-11-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0003_usuario_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Opcional 2'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Opcional 3'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_4',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Opcional 4'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_5',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Opcional 5'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_6',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Opcional 6'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_principal',
            field=models.ImageField(default='', upload_to='productos/', verbose_name='Imagen Principal'),
        ),
    ]
