# Generated by Django 5.0.9 on 2024-11-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0003_alter_carrito_tipo_alter_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='tipo',
            field=models.CharField(choices=[('E', 'En Proceso'), ('C', 'Completado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(max_length=20),
        ),
    ]
