# Generated by Django 5.0.9 on 2024-11-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0004_remove_producto_imagen_producto_imagen_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='tipo',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('VIDEOJUEGOS', [('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('XBOX-360', 'Xbox 360'), ('XBOX-ONE', 'Xbox One'), ('XBOX-SERIES', 'Xbox Series'), ('N3DS', 'Nintendo 3DS'), ('WII', 'Nintendo Wii'), ('WII-U', 'Nintendo Wii U'), ('SWITCH', 'Nintendo Switch'), ('PC', 'PC')]), ('CONSOLAS', [('PS4-CONSOLA', 'PlayStation 4'), ('PS5-CONSOLA', 'PlayStation 5'), ('XBOX-ONE-CONSOLA', 'Xbox One'), ('XBOX-SERIES-CONSOLA', 'Xbox Series'), ('WII-U-CONSOLA', 'Wii U'), ('SWITCH-CONSOLA', 'Switch')]), ('ACCESORIOS', [('PSP-ACCESORIOS', 'PSP'), ('PS-VITA-ACCESORIOS', 'PlayStation Vita'), ('PS1-ACCESORIOS', 'PlayStation 1'), ('PS2-ACCESORIOS', 'PlayStation 2'), ('PS3-ACCESORIOS', 'PlayStation 3'), ('PS4-ACCESORIOS', 'PlayStation 4'), ('PS5-ACCESORIOS', 'PlayStation 5'), ('XBOX-360-ACCESORIOS', 'Xbox 360'), ('XBOX-ONE-ACCESORIOS', 'Xbox One'), ('XBOX-SERIES-ACCESORIOS', 'Xbox Series'), ('N3DS-ACCESORIOS', 'Nintendo 3DS'), ('WII-U-ACCESORIOS', 'Wii U'), ('SWITCH-ACCESORIOS', 'Switch')]), ('FIGURAS', [('FUNKO', 'Funko Pop'), ('AMIIBO', 'Amiibo')])], max_length=40, verbose_name='Categoría'),
        ),
    ]
