# Generated by Django 5.0.9 on 2024-11-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0005_rename_tipo_carrito_estado_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(default='', max_length=25),
        ),
    ]
