# Generated by Django 5.0.9 on 2024-11-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0005_alter_carrito_tipo_alter_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='tipo',
            field=models.CharField(blank=True, choices=[('E', 'En Proceso'), ('C', 'Completado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
