# Generated by Django 5.0.9 on 2024-11-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0006_producto_genero_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('RPG', 'RPG'), ('DEPORTES', 'Deportes'), ('CARRERAS', 'Carreras'), ('ESTRATEGIA', 'Estrategia'), ('SIMULACION', 'Simulación'), ('PUZZLE', 'Puzzle'), ('TERROR', 'Terror'), ('CONSOLAS', 'Consolas'), ('FIGURAS', 'Figuras'), ('ACCESORIOS', 'Accesorios'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Género'),
        ),
    ]
