# Generated by Django 5.0.9 on 2024-11-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0007_alter_producto_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default='Rut no especificado', max_length=12, verbose_name='RUT'),
        ),
    ]
