# Generated by Django 5.0.9 on 2024-11-24 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0008_usuario_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='carrito',
        ),
        migrations.AddField(
            model_name='venta',
            name='direccion_envio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_envio',
            field=models.CharField(choices=[('domicilio', 'Envío a domicilio'), ('tienda', 'Retiro en tienda')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(related_name='ventas', to='appPrincipal.itemcarritoproducto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='appPrincipal.usuario'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Fallido', 'Fallido')], default='Pendiente', max_length=20),
        ),
    ]
