# Generated by Django 5.0.9 on 2024-11-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0008_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default='Rut no especificado', max_length=12, unique=True, verbose_name='RUT'),
        ),
    ]
