# Generated by Django 5.0.9 on 2024-11-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0008_alter_producto_descripcion_alter_reclamo_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='estado',
        ),
    ]
