# Generated by Django 5.0.9 on 2024-11-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0009_remove_carrito_tipo_remove_venta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='tipo',
            field=models.CharField(blank=True, choices=[('E', 'En Proceso'), ('C', 'Completado')], default='E', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(blank=True, default='Pendiente', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemcarritoproducto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_de_barra',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
