# Generated by Django 5.0.9 on 2024-11-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0009_remove_venta_carrito_venta_direccion_envio_and_more'),
        ('appPrincipal', '0010_alter_usuario_rut'),
    ]

    operations = [
    ]
