# Generated by Django 5.0.9 on 2024-11-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0011_merge_20241124_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='estado',
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('Sin Enviar', 'Sin Enviar'), ('Enviado', 'Enviado')], default='Sin Enviar', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(related_name='ventas', to='appPrincipal.itemcarritoproducto', verbose_name='Productos'),
        ),
    ]
