# Generated by Django 5.0.9 on 2024-11-24 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0012_remove_carrito_estado_alter_venta_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.carrito'),
        ),
    ]
