# Generated by Django 5.0.9 on 2024-11-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0012_alter_usuario_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
