# Generated by Django 5.0.9 on 2024-11-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0013_venta_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='referencia_externa',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
