# Generated by Django 5.0.9 on 2024-11-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0013_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_de_barra',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de Barra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=120, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
