# Generated by Django 5.0.9 on 2024-11-26 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0014_venta_referencia_externa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='referencia_externa',
        ),
    ]
