# Generated by Django 5.0.9 on 2024-11-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0014_alter_producto_codigo_de_barra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_de_barra',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código de Barra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='descripcion',
            field=models.TextField(default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
