# Generated by Django 5.0.9 on 2024-11-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0015_remove_venta_referencia_externa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='envio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
