# Generated by Django 5.0.9 on 2024-11-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0016_venta_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
