# Generated by Django 5.0.9 on 2024-11-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0018_favorito_listadeseados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Respondido', 'Respondido')], default='Abierto', max_length=20),
        ),
    ]
