# Generated by Django 5.0.9 on 2024-11-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0019_alter_reclamo_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListaDeseados',
        ),
    ]
