# Generated by Django 5.0.9 on 2024-11-27 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0020_delete_listadeseados'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='asunto',
            field=models.CharField(default='No especificado', max_length=255),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
